###
GET  http://localhost:8080/odata/v4/CatalogService/Books

###
POST  http://localhost:8080/odata/v4/CatalogService/Books
Content-Type: application/json

{ "title" : "aaa", "stock" : 222 }




# ###
# GET http://localhost:8080/odata/v4/CatalogService/addBooks
# Content-Type: application/json

# {   
#     "title": 1,
#     "stock": "TechEd"
#     "children": [
#         {"ID": 10, "name": "CAP Java", "descr": "Run on Java"}, 
#         {"ID": 11, "name": "CAP Node.js", "descr": "Run on Node.js"}
#     ]
# }

